### ISSUE TITLE
miss test_coords.pickle in 2D BCNN

### ISSUE THREAD

**Issue by kai-zhang-er** [sandialabs/bcnn#3]
How to generate test_coords.pickle for 2D BCNN? Does it have any impact on the prediction procedure? Thank you.

**Comment by tmlabonte** [comment]
`test_coords.pickle` is a file containing the original coordinates of each "chunk" of a 3D volume inside the larger original volume. We predict on each chunk individually, then refer to `test_coords.pickle` to reconstruct the entire prediction on the original volume. For a 2D BCNN, `test_coords.pickle` will not be generated because you do not need to chunk 2D data (it is usually small enough to fit in memory already).

Are you running into an error?

**Comment by kai-zhang-er** [comment]
I have solved the problem. Thank you very much. Would you like to publish your pretrained model for the 2D BCNN? I want to use the uncertainty map to evaluate my experiment.

**Comment by tmlabonte** [comment]
Unfortunately we are unable to publish our pretrained models as they are trained on proprietary datasets. Feel free to use the instructions in the README to train on your own dataset.
